alxgripper_leds:
  - id: 5
    position: [-0.257, 0.073, 0.28]
  - id: 6
    position: [-0.125, 0.073, 0.28]
  - id: 11
    position: [-0.067, 0.00, 0.28]
  - id: 12
    position: [-0.125, -0.106, 0.28]
  - id: 13
    position: [-0.257, -0.106, 0.28]
