#!/bin/bash
SCRIPTPATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
filename=$(ls $SCRIPTPATH/src/cepheus_robot/bags -t | head -1)
printf "Exporting from topics from latest bag file: %s\n" "$filename"
# printf "[ 1/41] exporting secs.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /secs > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.secs.txt"
# printf "exported\n"
# printf "[ 2/41] exporting set_ls_effort.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /set_left_shoulder_effort > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.set_ls_effort.txt"
# printf "exported\n"
# printf "[ 3/41] exporting set_le_effort.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /set_left_elbow_effort > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.set_le_effort.txt"
# printf "exported\n"
# printf "[ 4/41] exporting set_re_effort.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /set_right_elbow_effort > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.set_re_effort.txt"
# printf "exported\n"
# printf "[ 5/41] exporting set_rw_effort.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /set_reaction_wheel_effort > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.set_rw_effort.txt"
# printf "exported\n"

# printf "[ 6/41] exporting ls_pos.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /left_shoulder_pos > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.ls_pos.txt"
# printf "exported\n"
# printf "[ 7/41] exporting le_pos.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /left_elbow_pos > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.le_pos.txt"
# printf "exported\n"
# printf "[ 8/41] exporting re_pos.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /right_elbow_pos > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.re_pos.txt"
# printf "exported\n"

# printf "[ 9/41] exporting ls_vel.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /left_shoulder_vel > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.ls_vel.txt"
# printf "exported\n"
# printf "[10/41] exporting le_vel.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /left_elbow_vel > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.le_vel.txt"
# printf "exported\n"
# printf "[11/41] exporting re_vel.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /right_elbow_vel > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.re_vel.txt"
# printf "exported\n"

# printf "[12/41] exporting g_x.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /g_x > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.g_x.txt"
# printf "exported\n"
# printf "[13/41] exporting g_y.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /g_y > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.g_y.txt"
# printf "exported\n"
# printf "[14/41] exporting g_th.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /g_th > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.g_th.txt"
# printf "exported\n"
# printf "[15/41] exporting c_th.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /c_th > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.c_th.txt"
# printf "exported\n"
# printf "[16/41] exporting c_th_dot.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /c_th_dot > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.c_th_dot.txt"
# printf "exported\n"

# printf "[17/41] exporting qe_des_x.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /qe_des_x > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.qe_des_x.txt"
# printf "exported\n"
# printf "[18/41] exporting qe_des_y.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /qe_des_y > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.qe_des_y.txt"
# printf "exported\n"
# printf "[19/41] exporting qe_des_th.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /qe_des_th > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.qe_des_th.txt"
# printf "exported\n"

# printf "[20/41] exporting qe_dot_des_x.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /qe_dot_des_x > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.qe_dot_des_x.txt"
# printf "exported\n"
# printf "[21/41] exporting qe_dot_des_y.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /qe_dot_des_y > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.qe_dot_des_y.txt"
# printf "exported\n"
# printf "[22/41] exporting qe_dot_des_th.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /qe_dot_des_th > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.qe_dot_des_th.txt"
# printf "exported\n"

# # printf "[23/41] exporting qe_dotdot_des_x.txt... "
# # rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /qe_dotdot_des_x > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.qe_dotdot_des_x.txt"
# # printf "exported\n"
# # printf "[24/41] exporting qe_dotdot_des_y.txt... "
# # rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /qe_dotdot_des_y > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.qe_dotdot_des_y.txt"
# # printf "exported\n"
# # printf "[25/41] exporting qe_dotdot_des_th.txt... "
# # rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /qe_dotdot_des_th > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.qe_dotdot_des_th.txt"
# # printf "exported\n"

printf "[26/41] exporting fextx.txt... "
rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /fextx > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.fextx.txt"
printf "exported\n"
printf "[27/41] exporting fexty.txt... "
rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /fexty > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.fexty.txt"
printf "exported\n"
printf "[27/41] exporting fextz.txt... "
rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /fextz > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.fextz.txt"
printf "exported\n"
printf "[28/41] exporting next.txt... "
rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /next > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.next.txt"
printf "exported\n"
printf "[28/41] exporting nexty.txt... "
rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /nexty > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.nexty.txt"
printf "exported\n"
printf "[28/41] exporting nextx.txt... "
rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /nextx > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.nextx.txt"
printf "exported\n"

# printf "[29/41] exporting g_x_dot.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /g_x_dot > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.g_x_dot.txt"
# printf "exported\n"
# printf "[30/41] exporting g_y_dot.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /g_y_dot > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.g_y_dot.txt"
# printf "exported\n"
# printf "[31/41] exporting g_th_dot.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /g_th_dot > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.g_th_dot.txt"
# printf "exported\n"

# # printf "[32/41] exporting det.txt... "
# # rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /det > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.det.txt"
# # printf "exported\n"

# # printf "[33/41] exporting c_th_des.txt... "
# # rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /c_th_des > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.c_th_des.txt"
# # printf "exported\n"

# # printf "[34/41] exporting det_h.txt... "
# # rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /det_h > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.det_h.txt"
# # printf "exported\n"

# # printf "[35/41] exporting uRWn.txt... "
# # rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /uRWn > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.uRWn.txt"
# # printf "exported\n"
# # printf "[36/41] exporting umrX.txt... "
# # rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /umrX > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.umrX.txt"
# # printf "exported\n"
# # printf "[37/41] exporting umrY.txt... "
# # rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /umrY > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.umrY.txt"
# # printf "exported\n"
# # printf "[38/41] exporting umwn.txt... "
# # rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /umwn > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.umwn.txt"
# # printf "exported\n"

# printf "[39/41] exporting botarm_force_x.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /botarm_force_x > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.botarm_force_x.txt"
# printf "exported\n"
# printf "[40/41] exporting botarm_force_z.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /botarm_force_z > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.botarm_force_z.txt"
# printf "exported\n"
# printf "[41/41] exporting botarm_torque_y.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /botarm_torque_y > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.botarm_torque_y.txt"
# printf "exported\n"

python3 export_data.py
