#!/bin/bash
SCRIPTPATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"
filename=$(ls $SCRIPTPATH/src/cepheus_robot/bags -t | head -1)
printf "Exporting from topics from latest bag file: %s\n" "$filename"
printf "[ 1/23] exporting secs.txt... "
rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /secs > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.secs.txt"
printf "exported\n"
printf "[ 2/23] exporting set_ls_effort.txt... "
rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /set_left_shoulder_effort > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.set_ls_effort.txt"
printf "exported\n"
printf "[ 3/23] exporting set_le_effort.txt... "
rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /set_left_elbow_effort > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.set_le_effort.txt"
printf "exported\n"
printf "[ 4/23] exporting set_re_effort.txt... "
rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /set_right_elbow_effort > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.set_re_effort.txt"
printf "exported\n"
# printf "[ 5/23] exporting read_ls_position.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /read_left_shoulder_position > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.read_ls_position.txt"
# printf "exported\n"
# printf "[ 6/23] exporting read_le_position.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /read_left_elbow_position > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.read_le_position.txt"
# printf "exported\n"
# printf "[ 7/23] exporting read_re_position.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /read_right_elbow_position > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.read_re_position.txt"
# printf "exported\n"
# printf "[ 8/23] exporting read_ls_velocity.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /read_left_shoulder_velocity > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.read_ls_velocity.txt"
# printf "exported\n"
# printf "[ 9/23] exporting read_le_velocity.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /read_left_elbow_velocity > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.read_le_velocity.txt"
# printf "exported\n"
# printf "[10/23] exporting read_re_velocity.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /read_right_elbow_velocity > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.read_re_velocity.txt"
# printf "exported\n"
printf "[11/23] exporting set_ls_qd.txt... "
rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /set_left_shoulder_qd > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.set_ls_qd.txt"
printf "exported\n"
printf "[12/23] exporting set_le_qd.txt... "
rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /set_left_elbow_qd > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.set_le_qd.txt"
printf "exported\n"
printf "[13/23] exporting set_re_qd.txt... "
rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /set_right_elbow_qd > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.set_re_qd.txt"
printf "exported\n"

printf "[14/23] exporting ls_pos.txt... "
rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /left_shoulder_pos > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.ls_pos.txt"
printf "exported\n"
printf "[15/23] exporting le_pos.txt... "
rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /left_elbow_pos > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.le_pos.txt"
printf "exported\n"
printf "[16/23] exporting re_pos.txt... "
rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /right_elbow_pos > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.re_pos.txt"
printf "exported\n"

# printf "[17/23] exporting ls_vel.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /left_shoulder_vel > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.ls_vel.txt"
# printf "exported\n"
# printf "[18/23] exporting le_vel.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /left_elbow_vel > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.le_vel.txt"
# printf "exported\n"
# printf "[19/23] exporting re_vel.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /right_elbow_vel > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.re_vel.txt"
# printf "exported\n"

printf "[20/23] exporting ls_error.txt... "
rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /ls_error > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.ls_error.txt"
printf "exported\n"
printf "[21/23] exporting le_error.txt... "
rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /le_error > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.le_error.txt"
printf "exported\n"
printf "[22/23] exporting re_error.txt... "
rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /re_error > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.re_error.txt"
printf "exported\n"

# printf "[24/25] exporting FSR_soft.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /FSR_soft > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.FSR_soft.txt"
# printf "exported\n"
# printf "[25/25] exporting FSR_hard.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /FSR_hard > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.FSR_hard.txt"
# printf "exported\n"

# printf "[24/25] exporting g_x.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /g_x > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.g_x.txt"
# printf "exported\n"
# printf "[25/25] exporting g_y.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /g_y > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.g_y.txt"
# printf "exported\n"
# printf "[25/25] exporting g_th.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /g_th > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.g_th.txt"
# printf "exported\n"

# printf "[24/25] exporting g_x_dot.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /g_x_dot > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.g_x_dot.txt"
# printf "exported\n"
# printf "[25/25] exporting g_y_dot.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /g_y_dot > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.g_y_dot.txt"
# printf "exported\n"
# printf "[25/25] exporting g_th_dot.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /g_th_dot > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.g_th_dot.txt"
# printf "exported\n"

# printf "[25/25] exporting c_x.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /c_x > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.c_x.txt"
# printf "exported\n"
# printf "[25/25] exporting c_y.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /c_y > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.c_y.txt"
# printf "exported\n"
# printf "[25/25] exporting c_th.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /c_th > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.c_th.txt"
# printf "exported\n"

# printf "[24/25] exporting g_error_x.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /g_error_x > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.g_error_x.txt"
# printf "exported\n"
# printf "[25/25] exporting g_error_y.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /g_error_y > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.g_error_y.txt"
# printf "exported\n"
# printf "[25/25] exporting g_error_th.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /g_error_th > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.g_error_th.txt"
# printf "exported\n"

# printf "[24/25] exporting g_x_desdot.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /g_x_desdot > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.g_x_desdot.txt"
# printf "exported\n"

# printf "[25/25] exporting det.txt... "
# rostopic echo -b "$SCRIPTPATH/src/cepheus_robot/bags/$filename" -p /det > "$SCRIPTPATH/src/cepheus_robot/bags/$filename.det.txt"
# printf "exported\n"

python3 export_data.py
